services:
  redis:
    image: redis:7-alpine
    container_name: research-tools-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - research-tools-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: research-tools-backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-development-key-change-in-production
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend
      - DATABASE_URL=sqlite:///app/db.sqlite3
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - backend_static:/app/staticfiles
      - backend_media:/app/media
      - backend_data:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - research-tools-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: research-tools-frontend
    ports:
      - "3080:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - research-tools-network

volumes:
  redis_data:
  backend_static:
  backend_media:
  backend_data:

networks:
  research-tools-network:
    driver: bridge