# /researchtools_streamlit/docker-compose.yml

services:
  researchtools:
    build: .
    container_name: researchtools_streamlit
    ports:
      - "8502:8502"
    # volumes: ["./data:/app/data"]  # example of mounting a data folder if needed

