# /researchtools_streamlit/docker-compose.yml

services:
  researchtools:
    build: .
    container_name: researchtools_streamlit
    ports:
      - "${STREAMLIT_PORT}:8502"
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    # volumes: ["./data:/app/data"]  # example of mounting a data folder if needed

  db:
    image: postgres:latest
    container_name: analysis_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

