name = "researchtoolspy-cleanup-cron"
main = "worker.js"
compatibility_date = "2025-09-30"

# Run daily at 3:00 AM UTC
[triggers]
crons = ["0 3 * * *"]

# Optional: Add environment variables if needed
# [vars]
# CLEANUP_URL = "https://researchtoolspy.pages.dev/api/content-intelligence/cleanup"
