name = "researchtoolspy"
compatibility_date = "2025-09-30"
pages_build_output_dir = "dist"

[env.production]
vars = { ENVIRONMENT = "production" }

# D1 Database (uncomment when ready to use)
# [[d1_databases]]
# binding = "DB"
# database_name = "researchtoolspy-db"
# database_id = "your-database-id"