name = "researchtoolspy"
compatibility_date = "2025-09-30"
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "researchtoolspy-dev"
database_id = "aa7d1fbd-23b2-4fc4-8271-4b0070bb24b3"

# KV Namespace binding for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "17796fa8100b419f8df5ad08b2a09d7a"

# KV Namespace for cache
[[kv_namespaces]]
binding = "CACHE"
id = "48afc9fe53a3425b8757e9dc526c359e"

# KV Namespace for AI configuration
[[kv_namespaces]]
binding = "AI_CONFIG"
id = "7b7c607eb739402884712b0b033e3e7d"

# R2 Bucket for file uploads
[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "researchtoolspy-uploads"

[env.production.vars]
ENVIRONMENT = "production"
ENABLE_AI_FEATURES = "true"
DEFAULT_AI_MODEL = "gpt-4o-mini"

[[env.production.d1_databases]]
binding = "DB"
database_name = "researchtoolspy-prod"
database_id = "a455c866-9d7e-471f-8c28-e3816f87e7e3"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "17796fa8100b419f8df5ad08b2a09d7a"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "48afc9fe53a3425b8757e9dc526c359e"

[[env.production.kv_namespaces]]
binding = "AI_CONFIG"
id = "7b7c607eb739402884712b0b033e3e7d"

[[env.production.r2_buckets]]
binding = "UPLOADS"
bucket_name = "researchtoolspy-uploads"