name = "researchtoolspy"
compatibility_date = "2025-09-30"
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "researchtoolspy-dev"
database_id = "aa7d1fbd-23b2-4fc4-8271-4b0070bb24b3"

# KV Namespace binding for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "placeholder"  # Will be created

# KV Namespace for cache
[[kv_namespaces]]
binding = "CACHE"
id = "placeholder"  # Will be created

# R2 Bucket for file uploads
[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "researchtoolspy-uploads"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "researchtoolspy-prod"
database_id = "a455c866-9d7e-471f-8c28-e3816f87e7e3"