-- Migration: 056-collection-jobs.sql
-- Description: Add collection jobs schema for OSINT Collection Agent
-- Created: 2026-02-04

-- Collection job tracking
CREATE TABLE IF NOT EXISTS collection_jobs (
  id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL,
  query TEXT NOT NULL,
  categories TEXT DEFAULT '["news","academic","government","social","technical"]', -- JSON array
  time_range TEXT DEFAULT 'year', -- day, week, month, year, all
  max_results INTEGER DEFAULT 100,
  status TEXT DEFAULT 'pending', -- pending, running, complete, error
  results_count INTEGER DEFAULT 0,
  batch_job_id TEXT, -- Links to analysis batch job after approval
  error_message TEXT,
  llm_used TEXT, -- 'openai' or 'local'
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  completed_at TEXT,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);

-- Individual search results for triage
CREATE TABLE IF NOT EXISTS collection_results (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  url TEXT NOT NULL,
  title TEXT,
  snippet TEXT,
  category TEXT, -- news, academic, government, social, technical
  source_domain TEXT,
  relevance_score INTEGER DEFAULT 50, -- 0-100
  published_date TEXT,
  engine TEXT, -- Which SearXNG engine found it
  approved INTEGER DEFAULT 0, -- 0=pending, 1=approved, -1=rejected
  approved_at TEXT,
  analysis_id TEXT, -- Links to content_intelligence after processing
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (job_id) REFERENCES collection_jobs(id) ON DELETE CASCADE
);

-- Expanded queries generated by agent
CREATE TABLE IF NOT EXISTS collection_queries (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  category TEXT NOT NULL,
  query TEXT NOT NULL,
  rationale TEXT,
  results_count INTEGER DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (job_id) REFERENCES collection_jobs(id) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_collection_jobs_workspace ON collection_jobs(workspace_id);
CREATE INDEX IF NOT EXISTS idx_collection_jobs_status ON collection_jobs(status);
CREATE INDEX IF NOT EXISTS idx_collection_results_job ON collection_results(job_id);
CREATE INDEX IF NOT EXISTS idx_collection_results_relevance ON collection_results(relevance_score DESC);
CREATE INDEX IF NOT EXISTS idx_collection_results_job_relevance ON collection_results(job_id, relevance_score DESC);
CREATE INDEX IF NOT EXISTS idx_collection_results_category ON collection_results(category);
CREATE INDEX IF NOT EXISTS idx_collection_results_approved ON collection_results(approved);
CREATE INDEX IF NOT EXISTS idx_collection_queries_job ON collection_queries(job_id);
