-- Migration 040: Research Question Generator
-- Creates table for storing research questions generated by the tool
-- Supports SMART + FINER criteria assessment, null/alternative hypotheses
-- Date: October 11, 2025

CREATE TABLE IF NOT EXISTS research_questions (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  workspace_id TEXT NOT NULL,

  -- Input: Basic context
  topic TEXT NOT NULL,
  purpose TEXT, -- JSON array: ["exploratory", "descriptive", etc.]
  project_type TEXT, -- "Academic thesis", "Policy report", etc.

  -- Input: 5 W's (stored as JSON for flexibility)
  five_ws TEXT NOT NULL, -- JSON: {who: {population, subgroups}, what: {variables, expectedOutcome}, where: {location, settings}, when: {timePeriod, studyType}, why: {importance, beneficiaries}}

  -- Input: Constraints & Resources
  duration TEXT, -- "3-6 months", "1-2 years", etc.
  resources TEXT, -- JSON array: ["existing datasets", "survey tools", etc.]
  experience_level TEXT, -- "beginner", "intermediate", "advanced", "expert"
  constraints TEXT, -- Free text: areas to avoid
  ethical_considerations TEXT, -- Free text: ethical concerns

  -- Output: AI-generated questions (JSON array of 3 questions)
  -- Each question includes: question text, SMART assessment, FINER assessment,
  -- null/alternative hypotheses, key variables, data collection methods, challenges
  generated_questions TEXT NOT NULL,

  -- User selection
  selected_question_index INTEGER, -- Which of the 3 generated questions was selected (0, 1, or 2)
  selected_question TEXT, -- The final selected/edited question text
  custom_edits TEXT, -- JSON: any custom modifications user made

  -- Status tracking
  status TEXT DEFAULT 'draft', -- 'draft', 'finalized', 'archived'

  -- Metadata
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),

  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_research_questions_user ON research_questions(user_id);
CREATE INDEX IF NOT EXISTS idx_research_questions_workspace ON research_questions(workspace_id);
CREATE INDEX IF NOT EXISTS idx_research_questions_status ON research_questions(status);
CREATE INDEX IF NOT EXISTS idx_research_questions_created ON research_questions(created_at);

-- Optional: Table for tracking research plans (Phase 2 - Future)
-- This is commented out for now, will be created in a future migration
/*
CREATE TABLE IF NOT EXISTS research_plans (
  id TEXT PRIMARY KEY,
  research_question_id TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  workspace_id TEXT NOT NULL,

  -- Plan content
  methodology TEXT NOT NULL, -- JSON: {type, approach, design}
  timeline TEXT NOT NULL, -- JSON: milestones, deadlines
  resources_plan TEXT, -- JSON: budget, personnel, equipment
  literature_review_plan TEXT, -- JSON: databases, search terms
  data_analysis_plan TEXT, -- JSON: statistical tests, software
  ethical_plan TEXT, -- JSON: IRB, consent, privacy
  dissemination_plan TEXT, -- JSON: journals, conferences

  -- Status
  status TEXT DEFAULT 'draft',

  -- Metadata
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),

  FOREIGN KEY (research_question_id) REFERENCES research_questions(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);
*/
